### ISSUE TITLE
Broken link for Wind Chart tool

### ISSUE THREAD

**Issue by paduszym** [Gorisek-Bros/docs#10]
Bug reproduction:
1. Go to https://docs.dsj24.pl/inrun/gates.html
2. Click link in "simple tool" in "TIP" box.
3. Page https://dsj24.pl/wind.html gives 404.

**Comment by Mensix** [comment]
👍

Are you an author of the Otepaa HS97 hill btw? :)

**Comment by paduszym** [comment]
Yep.

**Comment by Mensix** [comment]
Outstanding work you have made :) We have been admiring it a lot on DSJ4 dedicated Discord, if you want to join it, then here is an invite link: https://discord.gg/gvypN6gbY7. 

There are some hill making dedicated channels, and the community would like to help with improving your venue, because there are some flickerings left. 

BR :)
